language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
services: mongodb
env:
  - NODE_ENV=DEV
install:
  - npm install
before_script:
  - npm run build:prod
script:
  # - npm test
  - npm test
