version: "3"
services:
  app:
    container_name: docker-node-mongo
    restart: always
    # looks in current directory for docker file to build image
    build: .
    ports:
      - "1337:1337"
    links:
      - mongo
  mongo:
    container_name: mongo
    # pulls mongo image from docker hub since not building from docker file
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo